### ISSUE TITLE
Can not get nvme disk status In  Utilities->Disks Status

### ISSUE THREAD

**Issue by waterloo3122** [Corsinvest/cv4pve-admin#102]
### Bug type

Component

### Component name

Disk Status

### What happened?

<img width="1882" alt="image" src="https://github.com/Corsinvest/cv4pve-admin/assets/6322033/d07709d7-0a08-4d20-b150-272eff53a50f">
<img width="837" alt="image" src="https://github.com/Corsinvest/cv4pve-admin/assets/6322033/0c0b868c-ee0a-4112-adca-7f1cba4c1133">

### Expected behavior

show correct smart info for nvme disk

### Relevant log output

```shell
2024-04-19 15:23:41.773 +08:00 [ERR]  192.168.88.159 admin@local
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Linq.Queryable.AsQueryable[TElement](IEnumerable`1 source)
   at Corsinvest.AppHero.Core.MudBlazorUI.Shared.Components.DataGrid.DataGridManager`1.LoadServerData(GridState`1 state)
   at MudBlazor.MudDataGrid`1.InvokeServerLoadFunc()
   at MudBlazor.MudDataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-04-19 15:23:41.774 +08:00 [WRN] Unhandled exception rendering component: Value cannot be null. (Parameter 'source') 192.168.88.159 admin@local
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Linq.Queryable.AsQueryable[TElement](IEnumerable`1 source)
   at Corsinvest.AppHero.Core.MudBlazorUI.Shared.Components.DataGrid.DataGridManager`1.LoadServerData(GridState`1 state)
   at MudBlazor.MudDataGrid`1.InvokeServerLoadFunc()
   at MudBlazor.MudDataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-04-19 15:23:41.775 +08:00 [ERR] Value cannot be null. (Parameter 'source') 192.168.88.159 admin@local
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Linq.Queryable.AsQueryable[TElement](IEnumerable`1 source)
   at Corsinvest.AppHero.Core.MudBlazorUI.Shared.Components.DataGrid.DataGridManager`1.LoadServerData(GridState`1 state)
   at MudBlazor.MudDataGrid`1.InvokeServerLoadFunc()
   at MudBlazor.MudDataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Proxmox VE Version

8.1

### Version (bug)

1.1.0

### Version (working)

no

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Mac OSX

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by waterloo3122** [comment]
As far as I Know, compared to sata disk, nvme disk has a different smart-info format
For nmve disk
<img width="797" alt="image" src="https://github.com/Corsinvest/cv4pve-admin/assets/6322033/237b0042-5af0-4436-8f0d-b56ceec48731">
For SATA disk
<img width="796" alt="image" src="https://github.com/Corsinvest/cv4pve-admin/assets/6322033/f526f792-343b-41e4-95b1-1053c37dcc45">

**Comment by franklupo** [comment]
Fix in next release
