### ISSUE TITLE
Cluster Diagnostic Exception Time

### ISSUE THREAD

**Issue by pepo087** [Corsinvest/cv4pve-admin#106]
### Bug type

Non so se sia un bug oppure sbaglio qualcosa io, utilizzo docker su una macchina virtuale di Ubuntu Server su proxmox. 
Il job per il cluster usage non mi ha dato problemi, questo sì

### Component name

Cluster Diagnostic Exception Time

### The error is for the wrong time resolution

```
Corsinvest.ProxmoxVE.Api.PveResultException (UBSERVER:1)
got wrong time resolution (60 != 1800)

Corsinvest.ProxmoxVE.Api.PveResultException: got wrong time resolution (60 != 1800)
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToModel[T](Result result)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensionsAutoGen.GetAsync(PveRrddata item, String timeframe, String cf)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensions.GetAsync(PveRrddata item, RrdDataTimeFrame dataTimeFrame, RrdDataConsolidation dataConsolidation)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadStoragesAsync(PveNodeItem nodeApi)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadNodesAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.CollectAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
   at Corsinvest.ProxmoxVE.Admin.Diagnostic.Helper.Create(IServiceScope scope, String clusterName) in /src/src/Corsinvest.ProxmoxVE.Admin.Diagnostic/Helper.cs:line 87
   at Corsinvest.ProxmoxVE.Admin.Diagnostic.Job.Create(String clusterName) in /src/src/Corsinvest.ProxmoxVE.Admin.Diagnostic/Job.cs:line 16
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs
![Schermata 2024-06-04 alle 16 22 06](https://github.com/Corsinvest/cv4pve-admin/assets/48530804/be1fc049-b383-4541-b5b7-a6721f54f1bf)
![Schermata 2024-06-04 alle 16 21 26](https://github.com/Corsinvest/cv4pve-admin/assets/48530804/e325e996-5ae6-4c5b-86d2-f7bb5a6cab29)
(Object obj, BindingFlags invokeAttr)
```

### Expected behavior

The response of cronJob get fail

### Proxmox VE Version

8.2.2

### Version (bug)

1.1.1

### Version (working)

1.1.1

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
Ciao,
Se utilizzi la versione command line  https://github.com/Corsinvest/cv4pve-diag da errore?

grazie

**Comment by pepo087** [comment]
same
```
pompeo@debian:~$ sudo ./cv4pve-diag --output=Text --host=***.***.***.***:8006 --username=root@pam --password=***** execute
ERROR: got wrong time resolution (60 != 1800)

```

**Comment by pepo087** [comment]
prima mi ha detto tutto fino a fermarsi qui allego
[log.json](https://github.com/user-attachments/files/15739241/log.json)

`     }
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Method: GET, Url: https://***.***.***.***:8006/api2/json/nodes/pve/storage/back/status
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      StatusCode:          OK
      ReasonPhrase:        OK
      IsSuccessStatusCode: True
trce: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      {
        "data": {
          "used": 0,
          "shared": 1,
          "type": "pbs",
          "total": 0,
          "content": "backup",
          "active": 0,
          "enabled": 1,
          "avail": 0
        }
      }
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Method: GET, Url: https://***.***.***.***:/api2/json/nodes/pve/storage/back/rrddata?timeframe=day&cf=AVERAGE
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      StatusCode:          InternalServerError
      ReasonPhrase:        got wrong time resolution (60 != 1800)
      IsSuccessStatusCode: False
trce: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      {
        "data": null
      }
ERROR: got wrong time resolution (60 != 1800)
================ EXCEPTION ================ 
Corsinvest.ProxmoxVE.Api.PveResultException
got wrong time resolution (60 != 1800)
fail: Program[0]
      got wrong time resolution (60 != 1800)
      Corsinvest.ProxmoxVE.Api.PveResultException: got wrong time resolution (60 != 1800)
         at Corsinvest.ProxmoxVE.Api.ResultExtension.ToModel[T](Result result)
         at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensionsAutoGen.GetAsync(PveRrddata item, String timeframe, String cf)
         at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensions.GetAsync(PveRrddata item, RrdDataTimeFrame dataTimeFrame, RrdDataConsolidation dataConsolidation)
         at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadStoragesAsync(PveNodeItem nodeApi)
         at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadNodesAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
         at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.CollectAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
         at Program.<>c__DisplayClass0_0.<<<Main>$>g__GetInfo|2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Program.<>c__DisplayClass0_0.<<<Main>$>b__5>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
         at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToModel[T](Result result)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensionsAutoGen.GetAsync(PveRrddata item, String timeframe, String cf)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensions.GetAsync(PveRrddata item, RrdDataTimeFrame dataTimeFrame, RrdDataConsolidation dataConsolidation)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadStoragesAsync(PveNodeItem nodeApi)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadNodesAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.CollectAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__GetInfo|2>d.MoveNext()
--- End of stack trace from previous location ---
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by franklupo** [comment]
https://forum.proxmox.com/threads/proxmox-node-summary-show-graphics-always-blank.85332/
https://forum.proxmox.com/threads/graphs-arent-generated-anymore-in-gui.126385/

sembrerebbe un problema di data

**Comment by pepo087** [comment]
`Corsinvest.ProxmoxVE.Api.PveResultException: RRD error: rrdcached@unix:/var/run/rrdcached.sock: rrd_fetch_r failed: opening '/var/lib/rrdcached/db/pve2-storage/pve/back': No such file or directory
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToModel[T](Result result)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensionsAutoGen.GetAsync(PveRrddata item, String timeframe, String cf)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensions.GetAsync(PveRrddata item, RrdDataTimeFrame dataTimeFrame, RrdDataConsolidation dataConsolidation)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadStoragesAsync(PveNodeItem nodeApi)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.ReadNodesAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
   at Corsinvest.ProxmoxVE.Api.Extension.Utils.InfoHelper.CollectAsync(PveClient client, Boolean removeSecurity, Int32 tasksDay, Boolean tasksOnlyErrors, Boolean nodeReport)
   at Corsinvest.ProxmoxVE.Admin.Diagnostic.Helper.Create(IServiceScope scope, String clusterName) in /src/src/Corsinvest.ProxmoxVE.Admin.Diagnostic/Helper.cs:line 87
   at Corsinvest.ProxmoxVE.Admin.Diagnostic.Job.Create(String clusterName) in /src/src/Corsinvest.ProxmoxVE.Admin.Diagnostic/Job.cs:line 16
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)`

**Comment by franklupo** [comment]
Prova la nuova versione cv4pve-diag nei prossimi giorni aggiorno anche admin.

grazie
