### ISSUE TITLE
Telegram Bot - System.MissingMethodException

### ISSUE THREAD

**Issue by alfonsomarzano** [Corsinvest/cv4pve-admin#107]
### Bug type

Component

### Component name

cv4pve-botgram

### What happened?

- Configurato botgram su nuova installazione cv4pve-admin tramite GUI.
- Verificato token e chat_id.

**/Module/CorsinvestProxmoxVEAdminBotgramModule restituisce questo errore**
```
Start listening
Telegram
Bot User: @cv4pve_bot
Bot UserId: @redacted
Proxmox VE
Host: _redacted - verificato e sono corretti_
Username: _redacted_
Started bot in cluster _redacted_
System.MissingMethodException: Attempted to access a missing method.
at Corsinvest.ProxmoxVE.TelegramBot.Api.BotManager.ProcessMessage(Message message)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Corsinvest.ProxmoxVE.TelegramBot.Api.BotManager.ProcessMessage(Message message)
at Corsinvest.ProxmoxVE.TelegramBot.Api.BotManager.HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
at Telegram.Bot.Polling.DefaultUpdateHandler.HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
at Telegram.Bot.Polling.DefaultUpdateReceiver.ReceiveAsync(IUpdateHandler updateHandler, CancellationToken cancellationToken)
at Telegram.Bot.TelegramBotClientExtensions.ReceiveAsync(ITelegramBotClient botClient, IUpdateHandler updateHandler, ReceiverOptions receiverOptions, CancellationToken cancellationToken)
at Telegram.Bot.TelegramBotClientExtensions.<>c__DisplayClass126_0.<b__0>d.MoveNext()
``` 

### Expected behavior

Comando /help dovrebbe generare lista comandi
Pagina Telegram Bot su CV4PVE-Admin dovrebbe essere funzionante

### Proxmox VE Version

8.2.2

### Version (bug)

1.1.1

### What browsers are you seeing the problem on?

Microsoft Edge

### On what operating system are you experiencing the issue?

Windows, Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alfonsomarzano** [comment]
L'esecuzione di botgram in modalità standalone non genera la problematica.

**Comment by alfonsomarzano** [comment]
Il problema sembra essere legato a modifiche in Corsinvest/cv4pve-botgram.
Effettuando il rollback a 1.6.0 la exception scompare.
Chiaramente a causa di incompatibilità tra le due versioni ho dovuto forzare alcune modifiche.

**Comment by franklupo** [comment]
Quali modifiche?

**Comment by alfonsomarzano** [comment]
BotgramService.cs -> GetChats
42: public IReadOnlyDictionary<long, string> GetChats(string clusterName)
BotManager non ha la property Chats in 1.6.0
