### ISSUE TITLE
No HTTPS for CV4PVE-ADMIN

### ISSUE THREAD

**Issue by kenrmayfield** [Corsinvest/cv4pve-admin#67]
The URL for CV4PVE-ADMIN can only be HTTP?  HTTPS will not work.   I can not use
CV4PVE-ADMIN in a Live Business Environment if only HTTP is used to reach the URL for CV4PVE-ADMIN.

There also No Option to Turn OFF HTTP and Turn ON HTTPS or just use HTTPS completely.

When you try the URL with HTTPS, you will Receive the Error:
_Secure Connection Failed
An error occurred during a connection to 192.168.1.143:5000. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG 
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.
Learn more…_

I did also try Editing the the File appsettings.json and change "urls": "**http:**//0.0.0.0:5000", to "urls": "**https:**//0.0.0.0:5000",
however the Page will not come up.

This is a Great Tool however I can not use this in the Live Business Environment with the URL being HTTP due to the fact that anyone could SNIFF the Username and Password to the Tool since HTTP is Non Encrypted.

Thanks,
Kenneth

**Comment by franklupo** [comment]
hi,
thank you for your interest. Let's check how to resolve your request.

best reagrds

**Comment by kenrmayfield** [comment]
Frank,

I am doing a Follow Up?


Thanks,
Kenneth

**Comment by franklupo** [comment]
Sorry, I don't understand. What do you mean?

**Comment by kenrmayfield** [comment]
I was Referring to the Request that I made about HTTPS when I started this Post 5 Days Ago.

**Comment by matteocv** [comment]
Hello @kenrmayfield,
our development team is working on it, we will update you in this issue.

Best Regards,

**Comment by kenrmayfield** [comment]
I was wondering if Creating a NGINX SSL for Docker would Work?
I wanted to see what you think?  CV4PVE-ADMIN still only Accepted HTTP Request and would Fail on HTTPS Request.
I was wondering if there is something in the Code I Manipulated below is missing something or it will not work?

**I have Manipulated the Code Below with Steps:**

Step 1: Create Directory

Create a directory with the name "docker_ssl_proxy" to store the NGINX Configuration file and the certificate and key
 

 $ mkdir docker_ssl_proxy

 
Step 2: Change Directory to docker_ssl_proxy

You must be under this directory before executing the following steps (Commands).

 
Step 2.a: Use Signed Certificates

If you have Certificates you can simply copy the following 2 files in the Current Directory
key.pem
cert.pem

Step 2.b Create the Self-Signed Certificates (If needed)

Use OpenSSL to create a self-signed certificate, Following command will create a self-signed certificate and a private key with a validity of 365 days.

 $ openssl req -subj '/CN=localhost' -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365

 
Step 3: Find your container IP address
3.1: Find your Container ID. 

$ docker ps

It will list all the processes that are running and find out your Container Id.

 
3.2 Find IP Address

To find the container IP address from the host, you can run the command
NOTE:
<Container-ID>: replace this with the value that you get from Step 3.1
 
$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'    <contrainer-ID>
 

The response of the above command will be an IP address

 
Step 4: Create the NGINX configuration file

In the same directory (docker_ssl_proxy), create a Configuration File that will Proxy All the Traffic to your upstream server. The upstream server is the application server running a non-SSL connection. The SSL will be using NGINX, and all the traffic will be proxied to the host (using the IP address that you got in Step 3.2)

 
The Configuration File, which in this example is called "proxy_ssl.conf," but can have any name as long as it ends in .conf. 
Example file: proxy_ssl.conf
NOTE: 5000 is the Port for CV4PVE-ADMIN.
      The only thing you need to replace in this file is the Container IP Address. 
      This file simply instructs NginX to listen, with SSL and the correct Certs and       Keys, on port 443 and to proxy all the requests to the host on port 5000.

The File must have the following Contents below:
 
server {
  listen 443;
  ssl on;
  ssl_certificate /etc/nginx/conf.d/cert.pem;
  ssl_certificate_key /etc/nginx/conf.d/key.pem;
  location / {
  proxy_pass http://<Container IP>:5000;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $remote_addr;
 }
}

 

Step 5: Run the Docker Container

At this point, we have all the Configuration in place to Proxy the Traffic; we simply need to run the Docker Container with the following command.

 
$ docker run --name nginx_proxy -d -v pwd:/etc/nginx/conf.d -p 5000:443 nginx


NOTE: 5000 is the Port for CV4PVE-ADMIN
If you face issues, try to replace PWD in the command above with the Full Directory Path for "docker_ssl_proxy", where you have Config and Cert files. 
 

$docker run --name nginx_proxy -d -v <yourdirectory>:/etc/nginx/conf.d -p 5000:443 nginx

**Comment by franklupo** [comment]
you could use a docker compose

**Comment by kenrmayfield** [comment]
@matteocv 
Frank,

On my Previous Posting........what did you think about the Code to try to get HTTPS to work?

It will be the same Problem.........still No HTTPS.  Even if you use a Container, that does not change the Protocol.

**Comment by franklupo** [comment]
hi,
I didn't enable Forwarded. In the next release we will come up with an example for Nginx

best reagrds

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

I Sent you and Matteo a Email asking a Question about the Reverse Proxy.

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

I was checking back on Previous Comment.

**Comment by kenrmayfield** [comment]
@matteocv

Frank,


Sent Response Email.

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

Sent Response Email.   Checking back with you Guys.

**Comment by franklupo** [comment]
News?

**Comment by kenrmayfield** [comment]
@franklupo 
@matteocv 


Still having a Problem getting  HTTPS to work?

I tried: https://github.com/Corsinvest/cv4pve-admin/tree/main/src/Docker/Nginx/ReverseProxy

**Comment by kenrmayfield** [comment]
@franklupo
@matteocv

Still having a Problem getting HTTPS to work?

I tried: https://github.com/Corsinvest/cv4pve-admin/tree/main/src/Docker/Nginx/ReverseProxy

**Comment by Aterfax** [comment]
> @franklupo @matteocv
> 
> Still having a Problem getting HTTPS to work?
> 
> I tried: https://github.com/Corsinvest/cv4pve-admin/tree/main/src/Docker/Nginx/ReverseProxy

Set up a SWAG reverse proxy, HTTPS over port 5000. SSL all setup fine. Errors suggest the backend docker for CV4PVE seems to be incompatible with running in HTTPS in some manner.

Seeing in browser console: 
```
Uncaught (in promise) WebSocket is not in the OPEN state

[2023-10-24T17:50:53.720Z] Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
```

Seeing in docker logs:

```
[ERR] Navigation failed when changing the location to /login?key=d3f0d667-c2c7-4e7e-8676-REDACTED

**Comment by franklupo** [comment]
I found and fixed the problem for reverse proxy.

**Comment by Bradley-Radomski** [comment]
How can HTTPS be added to a Windows hosted instance?

**Comment by Bradley-Radomski** [comment]
While I appreciate the response, I was just curious if there was an option for using the Windows.exe application. We are not running it in Docker therefore cannot put it behind nginx 'easily'. Was just curious if there was a toggle that can be added to force HTTPS

**Comment by franklupo** [comment]
for now it is not our priority, but it is in the things to do

**Comment by bastiane273** [comment]
I would like to give you a give you an example config for traefik reverse proxy:
please contact me: be@cloudservice.gmbh

**Comment by franklupo** [comment]
attach a file in this chat

**Comment by bastiane273** [comment]
OK: I will write it here:
Please create a directory for placing following files: #any other directory will work also
mkdir /opt/containers/cv4pve
**vi .env**
TZ="Europe/Berlin"
APP_NAME=cv15
APP_PORT=5000
GLOBAL_DOMAIN=cso.gmbh
---
which means the app will be reached through cv15.cso.gmbh
--
**vi docker-compose.yml**
---
services:
  cv4pve:
    image: corsinvest/cv4pve-admin:1.2.0
    volumes:
      - ./cv4-data:/app/data
      - ./appsettings.json:/app/appsettings.json

    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.cv4pve.entrypoints: "websecure"
      traefik.http.routers.cv4pve.rule: "Host(`${APP_NAME}.${GLOBAL_DOMAIN}`)"
      traefik.http.routers.cv4pve.tls: "true"
      traefik.http.routers.cv4pve.tls.certresolver: "http_resolver"
      traefik.docker.network: "proxy"
      traefik.http.services.cv4pve-traefik.loadbalancer.server.port: "${APP_PORT}"

networks:
  proxy:
    external: true
--
Please have in mind, that you have defined a certificate-resolver
**vi traefik.yml** # This is part of traefik-configuration
providers:
  file:
    filename: "./dynamic_conf.yml"
    watch: true
--
vi dynamic_conf.yml # This is part of traefik-configuration
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
--
## Please have in mind that the network in this configuration is named by **proxy** and have to be defined in the traefik-docker-compose.yml

**Comment by kenrmayfield** [comment]
Nice Work!

@bastiane273 Can you also provide a Config for if CV4PVE-ADMIN is installed as a VM(Binary)?

@franklupo Frank what do you think?

**Comment by franklupo** [comment]
> volumes:
>       - ./cv4-data:/app/data
>       - ./appsettings.json:/app/appsettings.json
> 
>     networks:
>       - proxy
>     labels:

If you want, prepare a PR

Best regards

**Comment by franklupo** [comment]
> Nice Work!
> 
> [@bastiane273](https://github.com/bastiane273) Can you also provide a Config for if CV4PVE-ADMIN is installed as a VM(Binary)?
> 
> [@franklupo](https://github.com/franklupo) Frank what do you think?

Good

**Comment by franklupo** [comment]
@kenrmayfield

The new version 2.0.0-rc1 is currently only available in Docker.
I will release the binaries, but the configuration has changed from version 1; I now use PosgreSQL.
As noted at http://localhost:8000/cv4pve-admin/getting-started/, a script is available for Docker Compose to simplify installation.

For https: https://corsinvest.github.io/cv4pve-admin/https/
